apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application-demo
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-application-demo
  template:
    metadata:
      labels:
        app: web-application-demo
    spec:
      containers:
      - name: web-application-demo
        image: localhost:5000/web-app
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: web-application-demo-service
  namespace: web-app
spec:
  selector:
    app: web-application-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort
